# Generated by Django 2.1.7 on 2020-03-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_at', models.DateField(auto_created=True, auto_now_add=True, verbose_name='Дата поступления')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('unit', models.CharField(max_length=10, verbose_name='Ед. измерения')),
                ('type', models.CharField(max_length=255, verbose_name='Вид товара')),
                ('weight', models.FloatField(default=0, verbose_name='Вес')),
                ('volume', models.FloatField(default=0, verbose_name='Объём')),
                ('qty_per_pack', models.PositiveIntegerField(default=0, verbose_name='Количество в упаковке')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('distributor', models.CharField(max_length=255, verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
