# Generated by Django 3.0.3 on 2020-03-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='qty_per_pack',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество в упаковке'),
        ),
        migrations.AlterField(
            model_name='good',
            name='type',
            field=models.IntegerField(choices=[(1, 'Бытовая техника'), (2, 'Мебель'), (3, 'Книги'), (4, 'Продукты'), (5, 'Офисное оборудование')], verbose_name='Вид товара'),
        ),
        migrations.AlterField(
            model_name='good',
            name='unit',
            field=models.IntegerField(choices=[(1, 'шт.'), (2, 'литры.'), (2, 'кг.')], verbose_name='Ед. измерения'),
        ),
    ]
