# Generated by Django 3.0.3 on 2020-03-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0003_auto_20200308_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='delivery_at',
            field=models.DateField(auto_created=True, auto_now_add=True, verbose_name='Дата поступления'),
        ),
    ]
